language: node_js

node_js:
  - "6"

before_install:
  - sudo apt-get update -q
  - sudo apt-get install cmake g++ gdb -y
  - sudo apt-get install libavcodec-dev libavformat-dev libgtk2.0-dev libswscale-dev pkg-config -y

before_script:
  - bash scripts/build.sh

cache:
  directories:
    - node_modules/
    - opencv/