language: node_js

node_js:
  - "8"

before_script:
  - echo Installing OpenCV...
  - sudo apt-get install cmake g++ gdb -y
  - sudo apt-get install libavcodec-dev libavformat-dev libgtk2.0-dev libswscale-dev pkg-config -y
  - git clone https://github.com/opencv/opencv
  - cd opencv
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local ..
  - make
  - sudo make install
  - cd ..
  - echo OpenCV installed successfully
  - 
  - echo Installing Tesseract OCR...
  - sudo apt-get update -q
  - sudo apt-get install tesseract-ocr
  - echo Tesseract OCR installed successfully

cache:
  directories:
    - node_modules/
    - opencv/